spring:
  application:
    name: postfacto
  datasource:
    url: jdbc:postgresql://localhost/postfactodb
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 9000